name: 'Pull Request Checks'

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  npm-install-build-only:
    uses: craigiswayne/ci-cd/.github/workflows/_npm-install-build-lint-test.yml@v0.0.10
    with:
      run_lint: false
      test_command: 'test:ci'
