name: 'Pull Request Checks'

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  npm-actions:
    uses: craigiswayne/ci-cd/.github/workflows/_npm-install-build-lint-test.yml@v0.0.11
    with:
      run_lint: false
      test_command: 'test:ci'
      test_artifact_path: '["coverage/ohmyadmin"]'
      test_artifact_name: 'coverage_report'
